import {API_KEY} from '@env';
const url = 'https://api.themoviedb.org/3';

const apiKey = API_KEY;

const getGenreData = async (type: string, id: number, page?: number) => {
  const res = await fetch(
    `${url}/discover/${type}?api_key=${apiKey}&with_genres=${id}&language=en-US&page=${
      page || 1
    }`,
  );
  const data = await res.json();
  return data;
};
const getMovieTypeData = async (type: string) => {
  const res = await fetch(`${url}/movie/${type}?api_key=${apiKey}`);
  const data = await res.json();
  return data;
};
const getTVTypeData = async (type: string) => {
  const res = await fetch(`${url}/tv/${type}?api_key=${apiKey}`);
  const data = await res.json();
  return data;
};

const getPopularTv = async () => {
  const res = await fetch(`${url}/tv/popular?api_key=${apiKey}`);
  const data = await res.json();
  return data;
};

// const rt = [
//   [
//     {
//       adult: false,
//       backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
//       genre_ids: [Array],
//       id: 502356,
//       original_language: 'en',
//       original_title: 'The Super Mario Bros. Movie',
//       overview:
//         'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
//       popularity: 9065.306,
//       poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
//       release_date: '2023-04-05',
//       title: 'The Super Mario Bros. Movie',
//       video: false,
//       vote_average: 7.5,
//       vote_count: 631,
//     },
//     {
//       adult: false,
//       backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
//       genre_ids: [Array],
//       id: 76600,
//       original_language: 'en',
//       original_title: 'Avatar: The Way of Water',
//       overview:
//         'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
//       popularity: 4810.649,
//       poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
//       release_date: '2022-12-14',
//       title: 'Avatar: The Way of Water',
//       video: false,
//       vote_average: 7.7,
//       vote_count: 6947,
//     },
//     {
//       adult: false,
//       backdrop_path: '/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg',
//       genre_ids: [Array],
//       id: 700391,
//       original_language: 'en',
//       original_title: '65',
//       overview:
//         '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
//       popularity: 1918.606,
//       poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
//       release_date: '2023-03-02',
//       title: '65',
//       video: false,
//       vote_average: 6.3,
//       vote_count: 424,
//     },
//     {
//       adult: false,
//       backdrop_path: '/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg',
//       genre_ids: [Array],
//       id: 315162,
//       original_language: 'en',
//       original_title: 'Puss in Boots: The Last Wish',
//       overview:
//         'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
//       popularity: 1878.108,
//       poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
//       release_date: '2022-12-07',
//       title: 'Puss in Boots: The Last Wish',
//       video: false,
//       vote_average: 8.3,
//       vote_count: 5144,
//     },
//     {
//       adult: false,
//       backdrop_path: '/vSUls0b7dNhC7tJoExF1MBYWWyh.jpg',
//       genre_ids: [Array],
//       id: 816904,
//       original_language: 'es',
//       original_title: 'Momias',
//       overview:
//         'Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, stolen by ambitious archaeologist Lord Carnaby.',
//       popularity: 1725.865,
//       poster_path: '/qVdrYN8qu7xUtsdEFeGiIVIaYd.jpg',
//       release_date: '2023-01-05',
//       title: 'Mummies',
//       video: false,
//       vote_average: 7.1,
//       vote_count: 143,
//     },
//     {
//       adult: false,
//       backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
//       genre_ids: [Array],
//       id: 505642,
//       original_language: 'en',
//       original_title: 'Black Panther: Wakanda Forever',
//       overview:
//         'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
//       popularity: 956.696,
//       poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
//       release_date: '2022-11-09',
//       title: 'Black Panther: Wakanda Forever',
//       video: false,
//       vote_average: 7.3,
//       vote_count: 4498,
//     },
//     {
//       adult: false,
//       backdrop_path: '/8q9k9yENMtpvtDTQgBZMRXyhnqp.jpg',
//       genre_ids: [Array],
//       id: 640146,
//       original_language: 'en',
//       original_title: 'Ant-Man and the Wasp: Quantumania',
//       overview:
//         "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
//       popularity: 855.543,
//       poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
//       release_date: '2023-02-15',
//       title: 'Ant-Man and the Wasp: Quantumania',
//       video: false,
//       vote_average: 6.3,
//       vote_count: 1230,
//     },
//     {
//       adult: false,
//       backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
//       genre_ids: [Array],
//       id: 436270,
//       original_language: 'en',
//       original_title: 'Black Adam',
//       overview:
//         'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
//       popularity: 866.04,
//       poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
//       release_date: '2022-10-19',
//       title: 'Black Adam',
//       video: false,
//       vote_average: 7.1,
//       vote_count: 4668,
//     },
//     {
//       adult: false,
//       backdrop_path: '/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg',
//       genre_ids: [Array],
//       id: 646389,
//       original_language: 'en',
//       original_title: 'Plane',
//       overview:
//         'After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.',
//       popularity: 631.421,
//       poster_path: '/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg',
//       release_date: '2023-01-12',
//       title: 'Plane',
//       video: false,
//       vote_average: 6.9,
//       vote_count: 1063,
//     },
//     {
//       adult: false,
//       backdrop_path: '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg',
//       genre_ids: [Array],
//       id: 635302,
//       original_language: 'ja',
//       original_title: '劇場版「鬼滅の刃」無限列車編',
//       overview:
//         "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
//       popularity: 586.802,
//       poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
//       release_date: '2020-10-16',
//       title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
//       video: false,
//       vote_average: 8.3,
//       vote_count: 3034,
//     },
//     {
//       adult: false,
//       backdrop_path: '/1GGfWFp9hp4RUHRHxd505z9rVFa.jpg',
//       genre_ids: [Array],
//       id: 9607,
//       original_language: 'en',
//       original_title: 'Super Mario Bros.',
//       overview:
//         "Mario and Luigi, plumbers from Brooklyn, find themselves in an alternate universe where evolved dinosaurs live in hi-tech squalor. They're the only hope to save our universe from invasion by the dino dictator, Koopa.",
//       popularity: 625.609,
//       poster_path: '/cudfWiiFDxj8rq1Myolzv6yY3ah.jpg',
//       release_date: '1993-05-28',
//       title: 'Super Mario Bros.',
//       video: false,
//       vote_average: 4.3,
//       vote_count: 1038,
//     },
//     {
//       adult: false,
//       backdrop_path: '/qai0MnVwPYCwOPSAnHIHyzBVqnd.jpg',
//       genre_ids: [Array],
//       id: 776835,
//       original_language: 'en',
//       original_title: "The Magician's Elephant",
//       overview:
//         'Peter is searching for his long-lost sister when he crosses paths with a fortune teller in the market square. His one one question is: is his sister still alive? The answer, that he must find a mysterious elephant and the magician who will conjure it, sets Peter off on a journey to complete three seemingly impossible tasks that will change the face of his town forever.',
//       popularity: 552.892,
//       poster_path: '/cAoAgzOCxSytYBqqCQulhXNR3LB.jpg',
//       release_date: '2023-03-10',
//       title: "The Magician's Elephant",
//       video: false,
//       vote_average: 7.3,
//       vote_count: 93,
//     },
//     {
//       adult: false,
//       backdrop_path: '/9H7oVnG4P75bda0y1t7EGDoPnRD.jpg',
//       genre_ids: [Array],
//       id: 964426,
//       original_language: 'no',
//       original_title: 'Gulltransporten',
//       overview:
//         'Fredrik isn’t the bravest of men, but now he is faced with a great responsibility and an enormous task - to get the entire Norwegian gold reserve away from the Nazis during the invasion of Norway.',
//       popularity: 617.659,
//       poster_path: '/6E4LopmCMUXcMLIv7o3jw1xQrgJ.jpg',
//       release_date: '2022-12-15',
//       title: 'Gold Run',
//       video: false,
//       vote_average: 6.6,
//       vote_count: 21,
//     },
//     {
//       adult: false,
//       backdrop_path: '/2rVkDZFLN6DI5PAoraoe9m4IRMN.jpg',
//       genre_ids: [Array],
//       id: 493529,
//       original_language: 'en',
//       original_title: 'Dungeons & Dragons: Honor Among Thieves',
//       overview:
//         'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
//       popularity: 401.539,
//       poster_path: '/6LuXaihVIoJ5FeSiFb7CZMtU7du.jpg',
//       release_date: '2023-03-23',
//       title: 'Dungeons & Dragons: Honor Among Thieves',
//       video: false,
//       vote_average: 7.5,
//       vote_count: 325,
//     },
//     {
//       adult: false,
//       backdrop_path: '/yEQqrW61rwNuVRHTjgHOAU4dXNE.jpg',
//       genre_ids: [Array],
//       id: 675353,
//       original_language: 'en',
//       original_title: 'Sonic the Hedgehog 2',
//       overview:
//         'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
//       popularity: 386.084,
//       poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
//       release_date: '2022-04-08',
//       title: 'Sonic the Hedgehog 2',
//       video: false,
//       vote_average: 7.6,
//       vote_count: 3829,
//     },
//     {
//       adult: false,
//       backdrop_path: '/isGINC82PZmMblEJP2rBAvSlX37.jpg',
//       genre_ids: [Array],
//       id: 599019,
//       original_language: 'ru',
//       original_title: 'Большое путешествие. Специальная доставка',
//       overview:
//         'It has been a year since Mic Mic and Oscar returned from their incredible adventure. And now, after a diabolical plan by Vulture to sabotage the delivery of the Grizzly cub to his opponent in the American presidential elections, Mic Mic, Oscar, Panda teenager and Stork set off on another great adventure as they ride a zeppelin to return little Grizzly to its rightful parents and save the American elections and the whole continent from an erupting volcano.',
//       popularity: 304.047,
//       poster_path: '/dabXVfrAFfhDte8XVemom3mTJog.jpg',
//       release_date: '2022-10-07',
//       title: 'Big Trip 2: Special Delivery',
//       video: false,
//       vote_average: 6.5,
//       vote_count: 57,
//     },
//     {
//       adult: false,
//       backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
//       genre_ids: [Array],
//       id: 634649,
//       original_language: 'en',
//       original_title: 'Spider-Man: No Way Home',
//       overview:
//         'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
//       popularity: 337.767,
//       poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
//       release_date: '2021-12-15',
//       title: 'Spider-Man: No Way Home',
//       video: false,
//       vote_average: 8,
//       vote_count: 17153,
//     },
//     {
//       adult: false,
//       backdrop_path: '/53BC9F2tpZnsGno2cLhzvGprDYS.jpg',
//       genre_ids: [Array],
//       id: 736526,
//       original_language: 'no',
//       original_title: 'Troll',
//       overview:
//         'Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?',
//       popularity: 348.945,
//       poster_path: '/9z4jRr43JdtU66P0iy8h18OyLql.jpg',
//       release_date: '2022-12-01',
//       title: 'Troll',
//       video: false,
//       vote_average: 6.8,
//       vote_count: 1331,
//     },
//     {
//       adult: false,
//       backdrop_path: '/qdFrqXYH6PtyAVlegub7bpoSgro.jpg',
//       genre_ids: [Array],
//       id: 573171,
//       original_language: 'es',
//       original_title: 'Huevitos Congelados',
//       overview:
//         'Follow the adventures of Toto and his family, who will have to travel to the South Pole to fulfill their promise to return a polar bear and some Spanish penguins to their home. In order to fulfill the promise, they will have to overcome some obstacles that will teach them how important teamwork is.',
//       popularity: 367.331,
//       poster_path: '/gBBCBMXKzWRADtliUYfV69aVIcz.jpg',
//       release_date: '2022-12-14',
//       title: 'A Frozen Rooster',
//       video: false,
//       vote_average: 7.9,
//       vote_count: 258,
//     },
//     {
//       adult: false,
//       backdrop_path: '/hT9ZUwLN5tB2O7miBu1oIMJFqJT.jpg',
//       genre_ids: [Array],
//       id: 507086,
//       original_language: 'en',
//       original_title: 'Jurassic World Dominion',
//       overview:
//         'Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.',
//       popularity: 294.281,
//       poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
//       release_date: '2022-06-01',
//       title: 'Jurassic World Dominion',
//       video: false,
//       vote_average: 6.9,
//       vote_count: 4674,
//     },
//   ],
//   [
//     {
//       adult: false,
//       backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
//       genre_ids: [Array],
//       id: 76600,
//       original_language: 'en',
//       original_title: 'Avatar: The Way of Water',
//       overview:
//         'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
//       popularity: 4810.649,
//       poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
//       release_date: '2022-12-14',
//       title: 'Avatar: The Way of Water',
//       video: false,
//       vote_average: 7.7,
//       vote_count: 6947,
//     },
//     {
//       adult: false,
//       backdrop_path: '/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg',
//       genre_ids: [Array],
//       id: 700391,
//       original_language: 'en',
//       original_title: '65',
//       overview:
//         '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
//       popularity: 1918.606,
//       poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
//       release_date: '2023-03-02',
//       title: '65',
//       video: false,
//       vote_average: 6.3,
//       vote_count: 424,
//     },
//     {
//       adult: false,
//       backdrop_path: '/sgFDQwJTYMuUS7Ng4PAPB8nBf2j.jpg',
//       genre_ids: [Array],
//       id: 1084225,
//       original_language: 'en',
//       original_title: 'The Park',
//       overview:
//         'A dystopian coming-of-age movie focused on three kids who find themselves in an abandoned amusement park, aiming to unite whoever remains. With dangers lurking around every corner, they will do whatever it takes to survive their hellish Neverland.',
//       popularity: 1080.758,
//       poster_path: '/hR1jdCw0A9czgsbp45TASkjjBhA.jpg',
//       release_date: '2023-03-02',
//       title: 'The Park',
//       video: false,
//       vote_average: 5.6,
//       vote_count: 27,
//     },
//     {
//       adult: false,
//       backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
//       genre_ids: [Array],
//       id: 505642,
//       original_language: 'en',
//       original_title: 'Black Panther: Wakanda Forever',
//       overview:
//         'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
//       popularity: 956.696,
//       poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
//       release_date: '2022-11-09',
//       title: 'Black Panther: Wakanda Forever',
//       video: false,
//       vote_average: 7.3,
//       vote_count: 4498,
//     },
//     {
//       adult: false,
//       backdrop_path: '/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg',
//       genre_ids: [Array],
//       id: 1033219,
//       original_language: 'en',
//       original_title: 'Attack on Titan',
//       overview:
//         "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't trust that the Earthlings will leave in peace.",
//       popularity: 1100.962,
//       poster_path: '/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg',
//       release_date: '2022-09-30',
//       title: 'Attack on Titan',
//       video: false,
//       vote_average: 6.1,
//       vote_count: 48,
//     },
//     {
//       adult: false,
//       backdrop_path: '/8q9k9yENMtpvtDTQgBZMRXyhnqp.jpg',
//       genre_ids: [Array],
//       id: 640146,
//       original_language: 'en',
//       original_title: 'Ant-Man and the Wasp: Quantumania',
//       overview:
//         "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
//       popularity: 855.543,
//       poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
//       release_date: '2023-02-15',
//       title: 'Ant-Man and the Wasp: Quantumania',
//       video: false,
//       vote_average: 6.3,
//       vote_count: 1230,
//     },
//     {
//       adult: false,
//       backdrop_path: '/AsEgGeccI32SwMBkxpwhOkhbzmF.jpg',
//       genre_ids: [Array],
//       id: 1011679,
//       original_language: 'en',
//       original_title: 'Shark Side of the Moon',
//       overview:
//         'Decades ago, the USSR developed unkillable sharks and launched them to the moon. Today, a team of American astronauts will endure the fight of their lives.',
//       popularity: 709.874,
//       poster_path: '/v5CfpzxoJDkZxjZAizClFdlEF0U.jpg',
//       release_date: '2022-08-12',
//       title: 'Shark Side of the Moon',
//       video: false,
//       vote_average: 5.3,
//       vote_count: 116,
//     },
//     {
//       adult: false,
//       backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
//       genre_ids: [Array],
//       id: 436270,
//       original_language: 'en',
//       original_title: 'Black Adam',
//       overview:
//         'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
//       popularity: 866.04,
//       poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
//       release_date: '2022-10-19',
//       title: 'Black Adam',
//       video: false,
//       vote_average: 7.1,
//       vote_count: 4668,
//     },
//     {
//       adult: false,
//       backdrop_path: '/1GGfWFp9hp4RUHRHxd505z9rVFa.jpg',
//       genre_ids: [Array],
//       id: 9607,
//       original_language: 'en',
//       original_title: 'Super Mario Bros.',
//       overview:
//         "Mario and Luigi, plumbers from Brooklyn, find themselves in an alternate universe where evolved dinosaurs live in hi-tech squalor. They're the only hope to save our universe from invasion by the dino dictator, Koopa.",
//       popularity: 625.609,
//       poster_path: '/cudfWiiFDxj8rq1Myolzv6yY3ah.jpg',
//       release_date: '1993-05-28',
//       title: 'Super Mario Bros.',
//       video: false,
//       vote_average: 4.3,
//       vote_count: 1038,
//     },
//     {
//       adult: false,
//       backdrop_path: '/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg',
//       genre_ids: [Array],
//       id: 536554,
//       original_language: 'en',
//       original_title: 'M3GAN',
//       overview:
//         "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
//       popularity: 656.221,
//       poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
//       release_date: '2022-12-28',
//       title: 'M3GAN',
//       video: false,
//       vote_average: 7.4,
//       vote_count: 2340,
//     },
//     {
//       adult: false,
//       backdrop_path: '/jhi3K0rN46SSu9wEu6zYVCOeVtH.jpg',
//       genre_ids: [Array],
//       id: 1003580,
//       original_language: 'en',
//       original_title: 'Legion of Super-Heroes',
//       overview:
//         'Kara, devastated by the loss of Krypton, struggles to adjust to her new life on Earth. Her cousin, Superman, mentors her and suggests she leave their space-time to attend the Legion Academy in the 31st century, where she makes new friends and a new enemy: Brainiac 5. Meanwhile, she must contend with a mysterious group called the Dark Circle as it searches for a powerful weapon held in the Academy’s vault.',
//       popularity: 480.772,
//       poster_path: '/8M6bA5t2q5u1nWDTEIXuGDwvboW.jpg',
//       release_date: '2023-02-07',
//       title: 'Legion of Super-Heroes',
//       video: false,
//       vote_average: 6.3,
//       vote_count: 78,
//     },
//     {
//       adult: false,
//       backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
//       genre_ids: [Array],
//       id: 634649,
//       original_language: 'en',
//       original_title: 'Spider-Man: No Way Home',
//       overview:
//         'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
//       popularity: 337.767,
//       poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
//       release_date: '2021-12-15',
//       title: 'Spider-Man: No Way Home',
//       video: false,
//       vote_average: 8,
//       vote_count: 17153,
//     },
//     {
//       adult: false,
//       backdrop_path: '/hT9ZUwLN5tB2O7miBu1oIMJFqJT.jpg',
//       genre_ids: [Array],
//       id: 507086,
//       original_language: 'en',
//       original_title: 'Jurassic World Dominion',
//       overview:
//         'Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.',
//       popularity: 294.281,
//       poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
//       release_date: '2022-06-01',
//       title: 'Jurassic World Dominion',
//       video: false,
//       vote_average: 6.9,
//       vote_count: 4674,
//     },
//     {
//       adult: false,
//       backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
//       genre_ids: [Array],
//       id: 19995,
//       original_language: 'en',
//       original_title: 'Avatar',
//       overview:
//         'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
//       popularity: 311.372,
//       poster_path: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
//       release_date: '2009-12-15',
//       title: 'Avatar',
//       video: false,
//       vote_average: 7.6,
//       vote_count: 28865,
//     },
//     {
//       adult: false,
//       backdrop_path: '/uR0FopHrAjDlG5q6PZB07a1JOva.jpg',
//       genre_ids: [Array],
//       id: 610150,
//       original_language: 'ja',
//       original_title: 'ドラゴンボール超 スーパーヒーロー',
//       overview:
//         'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.',
//       popularity: 345.006,
//       poster_path: '/pi0iZOEHeA3ih4p1IwAG4x2DZNH.jpg',
//       release_date: '2022-06-11',
//       title: 'Dragon Ball Super: Super Hero',
//       video: false,
//       vote_average: 7.9,
//       vote_count: 2349,
//     },
//     {
//       adult: false,
//       backdrop_path: '/ujL5e6S2PSkPE3FNSNrPGlB2haF.jpg',
//       genre_ids: [Array],
//       id: 919873,
//       original_language: 'en',
//       original_title: 'Arctic Void',
//       overview:
//         'When the power mysteriously fails, and almost everyone vanishes from a small tourist vessel in the Arctic, fear becomes the master for the three who remain. Forced ashore, the men deteriorate in body and mind until a dark truth emerges that compels them to ally or perish.',
//       popularity: 154.501,
//       poster_path: '/2OkdcVn1wIgRA4zo8tTbn7NNDUT.jpg',
//       release_date: '2022-01-14',
//       title: 'Arctic Void',
//       video: false,
//       vote_average: 4.7,
//       vote_count: 19,
//     },
//     {
//       adult: false,
//       backdrop_path: '/afsYFdid9pnnRd6tTrHFUbHgXJn.jpg',
//       genre_ids: [Array],
//       id: 843794,
//       original_language: 'ko',
//       original_title: '정이',
//       overview:
//         'On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.',
//       popularity: 358.567,
//       poster_path: '/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg',
//       release_date: '2023-01-20',
//       title: 'JUNG_E',
//       video: false,
//       vote_average: 6.3,
//       vote_count: 420,
//     },
//     {
//       adult: false,
//       backdrop_path: '/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
//       genre_ids: [Array],
//       id: 766507,
//       original_language: 'en',
//       original_title: 'Prey',
//       overview:
//         'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
//       popularity: 252.968,
//       poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
//       release_date: '2022-08-02',
//       title: 'Prey',
//       video: false,
//       vote_average: 7.8,
//       vote_count: 5361,
//     },
//     {
//       adult: false,
//       backdrop_path: '/5wDBVictj4wUYZ31gR5WzCM9dLD.jpg',
//       genre_ids: [Array],
//       id: 877269,
//       original_language: 'en',
//       original_title: 'Strange World',
//       overview:
//         'A journey deep into an uncharted and treacherous land, where fantastical creatures await the legendary Clades—a family of explorers whose differences threaten to topple their latest, and by far most crucial, mission.',
//       popularity: 236.244,
//       poster_path: '/fHMqfsYyl3lskPK2RiFRwhzwuep.jpg',
//       release_date: '2022-11-23',
//       title: 'Strange World',
//       video: false,
//       vote_average: 6.5,
//       vote_count: 895,
//     },
//     {
//       adult: false,
//       backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
//       genre_ids: [Array],
//       id: 299536,
//       original_language: 'en',
//       original_title: 'Avengers: Infinity War',
//       overview:
//         'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
//       popularity: 237.923,
//       poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
//       release_date: '2018-04-25',
//       title: 'Avengers: Infinity War',
//       video: false,
//       vote_average: 8.3,
//       vote_count: 26666,
//     },
//   ],
// ];

export {getPopularTv, getMovieTypeData, getTVTypeData, getGenreData};
